### PR TITLE
create automatic emulator setup

### PR DESCRIPTION
**Pull request by SteffenLm**
Please test the setup on your system.

### CODE REVIEW

**Comment by lamaglio** [comment]
I have a question: would it be useful to move provide-firebase.ts from src/firebase folder also into the newly created folder firebase?

**Comment by lamaglio** [comment]
Works as expected and is great to have! 😊

**Comment by lamaglio** [comment]
I will approve and merge it as soon as you fixed the pipeline

**Comment by SteffenLm** [comment]
> I have a question: would it be useful to move provide-firebase.ts from src/firebase folder also into the newly created folder firebase?

I had to move the config files on the same folder level as src etc. otherwise the firebase github action won't work.
the firebase.json files etc. are needed for setting up firebase for development and deployment. so it is the config for firebase itself. it has nothing to do with the source code of the app. the provide firebase methods are source code to configure the angular app to work with firebase. i don't think it's good to mix config of firebase itself and source code in the same folder like firebase-data. But we can move the firebase folder inside source to another place inside src. what place would you like to make it sure that it is a global app functionality?

**Comment by lamaglio** [comment]
> > I have a question: would it be useful to move provide-firebase.ts from src/firebase folder also into the newly created folder firebase?
> 
> I had to move the config files on the same folder level as src etc. otherwise the firebase github action won't work. the firebase.json files etc. are needed for setting up firebase for development and deployment. so it is the config for firebase itself. it has nothing to do with the source code of the app. the provide firebase methods are source code to configure the angular app to work with firebase. i don't think it's good to mix config of firebase itself and source code in the same folder like firebase-data. But we can move the firebase folder inside source to another place inside src. what place would you like to make it sure that it is a global app functionality?

Ahh okay, now I understand it. Then I think the place inside src is perfect.

**Pull request merged**
